// inspiration: https://github.com/ndom91/react-timezone-select/blob/main/src/timezone-list.ts
// translated using ChatGPT

const allTimezones = {
  'Pacific/Samoa': 'サモア標準時',
  'Pacific/Honolulu': 'ハワイ標準時',
  'Pacific/Tahiti': 'タヒチ標準時',
  'America/Juneau': 'アラスカ標準時',
  'America/Los_Angeles': '米国太平洋標準時',
  'America/Phoenix': 'アリゾナ標準時',
  'America/Chihuahua': 'メキシコ北部標準時',
  'America/Chicago': '北米中部標準時',
  'America/Regina': 'サスカチュワン標準時',
  'America/Mexico_City': 'メキシコ中部標準時',
  'America/Belize': '中央アメリカ標準時',
  'America/New_York': '米国東部標準時',
  'America/Toronto': 'カナダ東部標準時',
  'America/Bogota': 'コロンビア標準時',
  'America/Caracas': 'ベネズエラ標準時',
  'America/Santiago': 'チリ標準時',
  'America/St_Johns': 'ニューファンドランド標準時',
  'America/Sao_Paulo': 'ブラジリア標準時',
  'America/Argentina/Buenos_Aires': 'アルゼンチン標準時',
  'America/Godthab': 'グリーンランド西部標準時',
  'Atlantic/South_Georgia': '南ジョージア標準時',
  'Atlantic/Azores': 'アゾレス標準時',
  'Atlantic/Cape_Verde': 'カーボベルデ標準時',
  GMT: '世界標準時',
  'Europe/London': 'イギリス標準時',
  'Europe/Dublin': 'アイルランド標準時',
  'Europe/Lisbon': 'ポルトガル標準時',
  'Europe/Madrid': 'スペイン標準時',
  'Africa/Casablanca': 'モロッコ標準時',
  'Europe/Paris': 'フランス標準時',
  'Europe/Berlin': 'ドイツ標準時',
  'Europe/Rome': 'イタリア標準時',
  'Europe/Stockholm': 'スウェーデン標準時',
  'Africa/Cairo': 'エジプト標準時',
  'Europe/Helsinki': '東ヨーロッパ標準時',
  'Asia/Jerusalem': 'イスラエル標準時',
  'Africa/Johannesburg': '南アフリカ標準時',
  'Europe/Moscow': 'モスクワ標準時',
  'Asia/Kuwait': 'ペルシャ湾標準時',
  'Africa/Nairobi': '東アフリカ標準時',
  'Asia/Baghdad': 'イラク標準時',
  'Asia/Tehran': 'イラン標準時',
  'Asia/Dubai': 'アラビア半島標準時',
  'Asia/Baku': 'アゼルバイジャン標準時',
  'Asia/Kabul': 'アフガニスタン標準時',
  'Asia/Karachi': 'パキスタン標準時',
  'Asia/Kolkata': 'インド標準時',
  'Asia/Kathmandu': 'ネパール標準時',
  'Asia/Dhaka': 'バングラデシュ標準時',
  'Asia/Yangon': 'ミャンマー標準時',
  'Asia/Bangkok': 'インドシナ標準時',
  'Asia/Hong_Kong': '香港標準時',
  'Asia/Singapore': 'シンガポール標準時',
  'Asia/Shanghai': '中国標準時',
  'Asia/Taipei': '台湾標準時',
  'Australia/Perth': '西オーストラリア標準時',
  'Asia/Seoul': '韓国標準時',
  'Asia/Tokyo': '日本標準時',
  'Australia/Adelaide': '中部オーストラリア標準時',
  'Australia/Sydney': '東部オーストラリア標準時',
  'Australia/Brisbane': '豪州東部標準時',
  'Pacific/Noumea': 'ニューカレドニア標準時',
  'Pacific/Fiji': 'フィジー標準時',
  'Pacific/Auckland': 'ニュージーランド標準時',
};

export default allTimezones;
